export interface CountryLanguageMapping {
  countryCode: string;
  countryName: string;
  flag: string;
  languages: {
    code: string;
    nativeName: string;
    englishName: string;
  }[];
}

/**
 * Accurate Country -> 1–2+ Flagship Native Languages Directory
 * Allows users & brands to pick a country and immediately switch into its authentic local language(s).
 */
export const COUNTRY_LANGUAGE_DIRECTORY: CountryLanguageMapping[] = [
  {
    countryCode: "ZA",
    countryName: "South Africa",
    flag: "🇿🇦",
    languages: [
      { code: "zu", nativeName: "isiZulu", englishName: "Zulu" },
      { code: "xh", nativeName: "isiXhosa", englishName: "Xhosa" },
      { code: "af", nativeName: "Afrikaans", englishName: "Afrikaans" },
      { code: "st", nativeName: "Sesotho", englishName: "Sesotho" },
      { code: "tn", nativeName: "Setswana", englishName: "Setswana" },
      { code: "nso", nativeName: "Sepedi", englishName: "Sepedi" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "NG",
    countryName: "Nigeria",
    flag: "🇳🇬",
    languages: [
      { code: "ha", nativeName: "Hausa", englishName: "Hausa" },
      { code: "yo", nativeName: "Yorùbá", englishName: "Yoruba" },
      { code: "ig", nativeName: "Igbo", englishName: "Igbo" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "KE",
    countryName: "Kenya & Tanzania",
    flag: "🇰🇪",
    languages: [
      { code: "sw", nativeName: "Kiswahili", englishName: "Swahili" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "ET",
    countryName: "Ethiopia",
    flag: "🇪🇹",
    languages: [
      { code: "am", nativeName: "አማርኛ", englishName: "Amharic" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "BW",
    countryName: "Botswana & Lesotho",
    flag: "🇧🇼",
    languages: [
      { code: "tn", nativeName: "Setswana", englishName: "Setswana" },
      { code: "st", nativeName: "Sesotho", englishName: "Sesotho" },
    ],
  },
  {
    countryCode: "EG",
    countryName: "Egypt, UAE & Saudi Arabia",
    flag: "🇪🇬",
    languages: [
      { code: "ar", nativeName: "العربية", englishName: "Arabic" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "FR",
    countryName: "France, Senegal & Côte d'Ivoire",
    flag: "🇫🇷",
    languages: [
      { code: "fr", nativeName: "Français", englishName: "French" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "BR",
    countryName: "Brazil, Portugal, Angola & Mozambique",
    flag: "🇧🇷",
    languages: [
      { code: "pt", nativeName: "Português", englishName: "Portuguese" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "ES",
    countryName: "Spain, Mexico & Latin America",
    flag: "🇪🇸",
    languages: [
      { code: "es", nativeName: "Español", englishName: "Spanish" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "DE",
    countryName: "Germany, Austria & Switzerland",
    flag: "🇩🇪",
    languages: [
      { code: "de", nativeName: "Deutsch", englishName: "German" },
      { code: "fr", nativeName: "Français", englishName: "French" },
    ],
  },
  {
    countryCode: "NL",
    countryName: "Netherlands & Belgium",
    flag: "🇳🇱",
    languages: [
      { code: "nl", nativeName: "Nederlands", englishName: "Dutch" },
      { code: "fr", nativeName: "Français", englishName: "French" },
    ],
  },
  {
    countryCode: "IT",
    countryName: "Italy",
    flag: "🇮🇹",
    languages: [
      { code: "it", nativeName: "Italiano", englishName: "Italian" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "IN",
    countryName: "India",
    flag: "🇮🇳",
    languages: [
      { code: "hi", nativeName: "हिन्दी", englishName: "Hindi" },
      { code: "ta", nativeName: "தமிழ்", englishName: "Tamil" },
      { code: "bn", nativeName: "বাংলা", englishName: "Bengali" },
    ],
  },
  {
    countryCode: "CN",
    countryName: "China, Taiwan & Singapore",
    flag: "🇨🇳",
    languages: [
      { code: "zh-CN", nativeName: "简体中文", englishName: "Simplified Chinese" },
      { code: "zh-TW", nativeName: "繁體中文", englishName: "Traditional Chinese" },
    ],
  },
  {
    countryCode: "JP",
    countryName: "Japan",
    flag: "🇯🇵",
    languages: [
      { code: "ja", nativeName: "日本語", englishName: "Japanese" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "KR",
    countryName: "South Korea",
    flag: "🇰🇷",
    languages: [
      { code: "ko", nativeName: "한국어", englishName: "Korean" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "TR",
    countryName: "Turkey",
    flag: "🇹🇷",
    languages: [
      { code: "tr", nativeName: "Türkçe", englishName: "Turkish" },
      { code: "en", nativeName: "English", englishName: "English" },
    ],
  },
  {
    countryCode: "PL",
    countryName: "Poland & Eastern Europe",
    flag: "🇵🇱",
    languages: [
      { code: "pl", nativeName: "Polski", englishName: "Polish" },
      { code: "uk", nativeName: "Українська", englishName: "Ukrainian" },
    ],
  },
];

/**
 * Rich Native Hero & Feed bundles for major country flagship languages
 * so switching to Afrikaans, Setswana, Sepedi, Kiswahili, Hausa, Yoruba, Igbo,
 * Amharic, Arabic, Hindi, Chinese, Japanese, Korean, Italian, Dutch, Turkish, etc.
 * translates the entire Home Hero, Zwepe Coin, Randy Trash Can, Feed, and Navbar.
 */
export const COUNTRY_FLAGSHIP_APP_BUNDLES: Record<
  string,
  {
    nav?: Record<string, string>;
    hero?: Record<string, string>;
    feed?: Record<string, string>;
  }
> = {
  af: {
    nav: {
      home: "Tuis",
      feed: "Stroom",
      scan: "Skandeer",
      brands: "Handelsmerke",
      awards: "Toekennings",
      dashboard: "Beheerpaneel",
      profile: "Profiel",
      messages: "Boodskappe",
      signIn: "Meld aan",
      signUp: "Registreer",
      signOut: "Meld af",
    },
    hero: {
      badge: "Die Handelsmerk-Barometer",
      headlineBlack: "Hou wat jou dien.",
      headlineGold: "Daag uit wat nie werk nie.",
      subtitle: "Stem Bêre (Stash) of Weggooi (Trash) oor jou ware handelsmerk-ervarings — die CX- & PR-sein wat tel.",
      tagline: "Elke uitspraak bring handelsmerke nader aan die mense wat hulle dien. Gee joune. 🔥",
      spinningZwepe: "Draai tans Zwepe-munt... kyk hoe dit tol en plat val!",
      droppingBin: "Val in die asblik... kletter en klap!",
      tapCoin: "Tik op die Goue Munt om Stashes te sien",
      tapBin: "Tik op die Asblik om Trashes te sien",
      allTiers: "Alle vlakke",
      superBrands: "Superhandelsmerke",
      nationalPowerhouses: "Nasionale Reuse",
      emergingChallengers: "Opkomende Uitdagers",
      localHeroes: "Plaaslike Helde",
      sortBy: "Sorteer volgens",
      trustScore: "Vertrouenspunt",
      brandTier: "Handelsmerkvlak",
      alphabetical: "Alfabeties",
      liveSentiment: "Lewendige Sentiment Oor Handelsmerke",
      liveSentimentDesc: "Ware verbruikersuitsprake wat vertrouenspunte intyds vorm.",
      searchOrBrowse: "Soek handelsmerke of blaai hieronder",
      gettingStashed: "Wat gebêre word (Stashed)",
      gettingTrashed: "Wat weggegooi word (Trashed)",
      sotAwards: "Die SOT-Toekennings",
      crowningBrand: "Bekroon die jaar se mees betroubare handelsmerk",
      seeStandings: "Sien lewendige ranglys",
      prTeamClaim: "PR- & Handelsmerkspanne: Eis jou bladsy",
      prTeamDesc: "Monitor sentiment, reageer op kliënte en verdien geverifieerde status.",
      goToDashboard: "Gaan na Beheerpaneel",
      joinConversation: "Sluit aan by die gesprek",
      realPeopleVerdicts: "Ware mense. Ware uitsprake. Nul betaalmure.",
      exploreFeed: "Verken Stroom",
      scanProduct: "Skandeer Produk",
      stashes: "Bêre (Stashes)",
      trashes: "Weggooi (Trashes)",
    },
    feed: {
      pulse: "Gemeenskapspols",
      title: "Stash Or Trash",
      subtitle: "Die Handelsmerk-Barometer. Plaas enigiets oor 'n handelsmerk en laat die gemeenskap intyds besluit.",
      hook: "Elke uitspraak bring handelsmerke nader aan hul mense.",
      searchPlaceholder: "Soek plasings of handelsmerke",
      allVerdicts: "Alle uitsprake",
      stashesOfDay: "Stashes van die Dag",
      trashesOfDay: "Trashes van die Dag",
      resetFilter: "Herstel filter",
    },
  },
  tn: {
    nav: {
      home: "Gae",
      feed: "Ditiro",
      scan: "Sekena",
      brands: "Mabokgoni",
      awards: "Dikhumagadi",
      dashboard: "Letlapa la Taolo",
      profile: "Poeletso",
      messages: "Melaetsa",
      signIn: "Tsena",
      signUp: "Ikwadise",
      signOut: "Tswa",
    },
    hero: {
      badge: "Sekala sa Tshepo ya Mabokgoni",
      headlineBlack: "Boloka se se go direlang.",
      headlineGold: "Kgalemela se se sa direng.",
      subtitle: "Tlhopha Boloka (Stash) kgotsa Latlha (Trash) ka maitemogelo a gago a nnete — lentswe la bareki le le botlhokwa.",
      tagline: "Katlholo nngwe le nngwe e atametsa mabokgoni kwa bathong. Ntsha ya gago. 🔥",
      tapCoin: "Tobetsa Ledi la Gauta go bona tse di Bolokilweng",
      tapBin: "Tobetsa Moteme wa Matlakala go bona tse di Latlhilweng",
      trustScore: "Tekanyetso ya Tshepo",
      liveSentiment: "Maikutlo a Setšhaba ka Nako ya Nnete",
      liveSentimentDesc: "Dikatlholo tsa bareki ba nnete tse di agang tshepo ya mabokgoni.",
      gettingStashed: "Tse di Bolokwang (Stashed)",
      gettingTrashed: "Tse di Latlhwang (Trashed)",
      sotAwards: "Dikhumagadi tsa SOT",
      goToDashboard: "Ya kwa Letlapeng la Kgwebo",
      exploreFeed: "Lebelela Ditiro",
      scanProduct: "Sekena Khoutu ya Sehlahiswa",
      stashes: "Boloka (Stashes)",
      trashes: "Latlha (Trashes)",
    },
  },
  nso: {
    nav: {
      home: "Gae",
      feed: "Dikagare",
      scan: "Sekena",
      brands: "Mabrande",
      awards: "Difoka",
      dashboard: "Dashboto",
      profile: "Boitsebišo",
      messages: "Melaetsa",
      signIn: "Tsena",
      signUp: "Ingwadiše",
      signOut: "Tšwa",
    },
    hero: {
      badge: "Sekala sa Tshepo ya Mabrande",
      headlineBlack: "Boloka seo se go thušago.",
      headlineGold: "Ganana le seo se sa šomego.",
      subtitle: "Kgetha Boloka (Stash) goba Lahla (Trash) go ya ka maitemogelo a gago a nnete le mabrande.",
      tagline: "Kahlolo ye nngwe le ye nngwe e batametša mabrande bathong. Neela ya gago. 🔥",
      tapCoin: "Kgwatha Tšhelete ya Gauta go bona tše Bolokilwego",
      tapBin: "Kgwatha Motomo wa Ditšhila go bona tše Lahlilwego",
      trustScore: "Tekanyetšo ya Tshepo",
      liveSentiment: "Maikutlo a Setšhaba Semeetseng",
      gettingStashed: "Tše di Bolokwago (Stashed)",
      gettingTrashed: "Tše di Lahlwago (Trashed)",
      sotAwards: "Difoka tša SOT",
      goToDashboard: "Ya go Dashboto",
      exploreFeed: "Lekola Dikagare",
      scanProduct: "Sekena Setšweletšwa",
      stashes: "Boloka (Stashes)",
      trashes: "Lahla (Trashes)",
    },
  },
  sw: {
    nav: {
      home: "Nyumbani",
      feed: "Mlisho",
      scan: "Changanua",
      brands: "Chapa",
      awards: "Tuzo",
      dashboard: "Dashibodi",
      profile: "Wasifu",
      messages: "Ujumbe",
      signIn: "Ingia",
      signUp: "Jisajili",
      signOut: "Toka",
    },
    hero: {
      badge: "Kipima Joto cha Chapa",
      headlineBlack: "Tunza kinachokufaa.",
      headlineGold: "Pinga kisichokufaa.",
      subtitle: "Piga kura ya Hifadhi (Stash) au Tupa (Trash) kuhusu uzoefu wako halisi wa chapa — sauti ya wateja inayojenga uaminifu.",
      tagline: "Kila uamuzi huleta chapa karibu na watu wanaowahudumia. Toa uamuzi wako. 🔥",
      tapCoin: "Gusa Sarafu ya Dhahabu kuona Zilizohifadhiwa",
      tapBin: "Gusa Pipani kuona Zilizotupwa",
      trustScore: "Alama ya Uaminifu",
      liveSentiment: "Hisia za Moja kwa Moja za Wateja",
      liveSentimentDesc: "Maamuzi halisi ya watumiaji yanayounda alama za uaminifu moja kwa moja.",
      gettingStashed: "Zinazohifadhiwa Zaidi",
      gettingTrashed: "Zinazotupwa Zaidi",
      sotAwards: "Tuzo za SOT",
      goToDashboard: "Nenda kwenye Dashibodi",
      exploreFeed: "Chunguza Mlisho",
      scanProduct: "Changanua Bidhaa",
      stashes: "Hifadhi (Stashes)",
      trashes: "Tupa (Trashes)",
    },
  },
  ha: {
    nav: {
      home: "Gida",
      feed: "Labarai",
      scan: "Bincika",
      brands: "Kamfanoni",
      awards: "Kyaututtuka",
      dashboard: "Allon Sarauta",
      profile: "Bayanai",
      messages: "Saƙonni",
      signIn: "Shiga",
      signUp: "Yi Rajista",
      signOut: "Fita",
    },
    hero: {
      badge: "Ma'aunin Amincewar Kamfanoni",
      headlineBlack: "Ajiye abin da ke amfanar ka.",
      headlineGold: "Ƙalubalanci abin da ba ya amfani.",
      subtitle: "Zaɓi Ajiye (Stash) ko Zubar (Trash) bisa gaskiyar mu'amalarka da kamfanoni a yau.",
      tagline: "Kowane hukunci yana kusantar da kamfanoni ga jama'a. Bayar da naka. 🔥",
      tapCoin: "Danna Kuɗin Zinariya don ganin Ajiyayyu",
      tapBin: "Danna Kwandon Shara don ganin Zubarwa",
      trustScore: "Makin Amana",
      liveSentiment: "Ra'ayin Jama'a Kai Tsaye",
      gettingStashed: "Abubuwan da ake Ajiyewa",
      gettingTrashed: "Abubuwan da ake Zubarwa",
      sotAwards: "Kyaututtukan SOT",
      goToDashboard: "Je zuwa Allon Kamfani",
      exploreFeed: "Duba Labarai",
      scanProduct: "Bincika Lambar Kaya",
      stashes: "Ajiye (Stashes)",
      trashes: "Zubar (Trashes)",
    },
  },
  yo: {
    nav: {
      home: "Ilé",
      feed: "Àfikún",
      scan: "Ṣàyẹ̀wò",
      brands: "Àwọn Ilé-iṣẹ́",
      awards: "Àwọn Àmì-ẹ̀yẹ",
      dashboard: "Pẹpẹ Iṣẹ́",
      profile: "Profaili",
      messages: "Àwọn Ifiranṣẹ",
      signIn: "Wọlé",
      signUp: "Forúkọsílẹ̀",
      signOut: "Jáde",
    },
    hero: {
      badge: "Iwọn Ìgbẹ́kẹ̀lé Àwọn Ilé-iṣẹ́",
      headlineBlack: "Tọ́jú ohun tí óטי wúlò fún ọ.",
      headlineGold: "Kọ ohun tí kò bá ọ mu.",
      subtitle: "Dìbò Tọ́jú (Stash) tàbí Dà nù (Trash) lórí ìrírí rẹ gidi pẹ̀lú àwọn ilé-iṣẹ́.",
      tagline: "Gbogbo ìdájọ́ ló ń mú ilé-iṣẹ́ sún mọ́ àwọn ènìyàn. Sọ tìrẹ. 🔥",
      tapCoin: "Tẹ Owó Wúrà láti rí Àwọn Tí A Tọ́jú",
      tapBin: "Tẹ Apẹ̀rẹ̀ Ìdọ̀tí láti rí Àwọn Tí A Dà Nù",
      trustScore: "Iye Ìgbẹ́kẹ̀lé",
      liveSentiment: "Èrò Àwọn Ènìyàn Lọ́wọ́lọ́wọ́",
      gettingStashed: "Ohun Tí Àwọn Ènìyàn Ń Tọ́jú",
      gettingTrashed: "Ohun Tí Àwọn Ènìyàn Ń Dà Nù",
      sotAwards: "Àwọn Àmì-ẹ̀yẹ SOT",
      goToDashboard: "Lọ sí Pẹpẹ Ilé-iṣẹ́",
      exploreFeed: "Wo Àfikún",
      scanProduct: "Ṣàyẹ̀wò Ọjà",
      stashes: "Tọ́jú (Stashes)",
      trashes: "Dà nù (Trashes)",
    },
  },
  ig: {
    nav: {
      home: "Ụlọ",
      feed: "Ihe ọhụrụ",
      scan: "Nyochaa",
      brands: "Ụdị Ngwaahịa",
      awards: "Ihe nrite",
      dashboard: "Mpempe Nlekọta",
      profile: "Profaịlụ",
      messages: "Ozi",
      signIn: "Banye",
      signUp: "Debanye aha",
      signOut: "Pụọ",
    },
    hero: {
      badge: "Ọ̀tụ̀tụ̀ Ntụkwasị Obi Ụdị Ngwaahịa",
      headlineBlack: "Chekwaa ihe na-enyere gị aka.",
      headlineGold: "Jụ ihe na-adịghị mma.",
      subtitle: "ịtụ vootu Chekwaa (Stash) ma ọ bụ Tụfuo (Trash) maka ahụmịhe gị na ụdị ngwaahịa.",
      tagline: "Mkpebi ọ bụla na-eme ka ụlọ ọrụ bịaruo ndị mmadụ nso. Nye nke gị. 🔥",
      tapCoin: "Pịa Mkpụrụ Egoọlaedo ka ịhụ Nke Echekwara",
      tapBin: "Pịa Ngịga Ahịhịa ka ịhụ Nke Atụfuru",
      trustScore: "Akara Ntụkwasị Obi",
      liveSentiment: "echiche Ndị Mmadụ Ozugbo",
      gettingStashed: "Ihe Ndị A Na-echekwa",
      gettingTrashed: "Ihe Ndị A Na-atụfu",
      sotAwards: "Ihe Nrite SOT",
      goToDashboard: "Gaa na Mpempe Nlekọta",
      exploreFeed: "Chọpụta Ihe Ọhụrụ",
      scanProduct: "Nyochaa Ngwaahịa",
      stashes: "Chekwaa (Stashes)",
      trashes: "Tụfuo (Trashes)",
    },
  },
  am: {
    nav: {
      home: "መነሻ",
      feed: "ምግቦች",
      scan: "ቃኝ",
      brands: "ብራንዶች",
      awards: "ሽልማቶች",
      dashboard: "ዳሽቦርድ",
      profile: "መገለጫ",
      messages: "መልዕክቶች",
      signIn: "ግባ",
      signUp: "ይመዝገቡ",
      signOut: "ውጣ",
    },
    hero: {
      badge: "የብራንድ እምነት መለኪያ",
      headlineBlack: "የሚጠቅምዎትን ያስቀምጡ።",
      headlineGold: "የማይጠቅምዎትን ይቃወሙ።",
      subtitle: "በእውነተኛ የብራንድ ተሞክሮዎ ላይ አስቀምጥ (Stash) ወይም ጣለው (Trash) ብለው ድምጽ ይስጡ።",
      tagline: "እያንዳንዱ ውሳኔ ብራንዶችን ከሕዝቡ ጋር ያቀራርባል። የእርስዎን ይስጡ። 🔥",
      tapCoin: "የተቀመጡትን ለማየት የወርቅ ሳንቲሙን ይንኩ",
      tapBin: "የተጣሉትን ለማየት የቆሻሻ መጣያውን ይንኩ",
      trustScore: "የእምነት ነጥብ",
      liveSentiment: "የቀጥታ የደንበኞች ስሜት",
      gettingStashed: "በብዛት የተቀመጡ",
      gettingTrashed: "በብዛት የተጣሉ",
      sotAwards: "የSOT ሽልማቶች",
      goToDashboard: "ወደ ዳሽቦርድ ይሂዱ",
      exploreFeed: "ምግቦችን ያስሱ",
      scanProduct: "ምርት ይቃኙ",
      stashes: "አስቀምጥ (Stashes)",
      trashes: "ጣለው (Trashes)",
    },
  },
  ar: {
    nav: {
      home: "الرئيسية",
      feed: "المنشورات",
      scan: "مسح المنتج",
      brands: "العلامات التجارية",
      awards: "الجوائز",
      dashboard: "لوحة التحكم",
      profile: "الملف الشخصي",
      messages: "الرسائل",
      signIn: "تسجيل الدخول",
      signUp: "إنشاء حساب",
      signOut: "خروج",
    },
    hero: {
      badge: "مقياس ثقة العلامات التجارية",
      headlineBlack: "احتفظ بما يخدمك.",
      headlineGold: "تحدَّ ما لا يخدمك.",
      subtitle: "صوّت بـ احتفاظ (Stash) أو استبعاد (Trash) بناءً على تجربتك الحقيقية مع العلامات التجارية.",
      tagline: "كل حكم يقرّب العلامات التجارية من عملائها. أدلِ بصوتك الآن. 🔥",
      tapCoin: "اضغط على العملة الذهبية لعرض المحتفظ بها",
      tapBin: "اضغط على السلة لعرض المستبعدة",
      trustScore: "مؤشر الثقة",
      liveSentiment: "نبض المستهلكين المباشر",
      gettingStashed: "الأكثر احتفاظاً",
      gettingTrashed: "الأكثر استبعاداً",
      sotAwards: "جوائز SOT",
      goToDashboard: "انتقل إلى لوحة العلامة",
      exploreFeed: "تصفح المنشورات",
      scanProduct: "افحص باركود المنتج",
      stashes: "احتفاظ (Stash)",
      trashes: "استبعاد (Trash)",
    },
  },
  hi: {
    nav: {
      home: "होम",
      feed: "फ़ीड",
      scan: "स्कैन करें",
      brands: "ब्रांड्स",
      awards: "पुरस्कार",
      dashboard: "डैशबोर्ड",
      profile: "प्रोफ़ाइल",
      messages: "संदेश",
      signIn: "साइन इन",
      signUp: "साइन अप",
      signOut: "साइन आउट",
    },
    hero: {
      badge: "ब्रांड विश्वास बैरोमीटर",
      headlineBlack: "जो आपके काम आए उसे रखें।",
      headlineGold: "जो सही न हो उसे चुनौती दें।",
      subtitle: "अपने वास्तविक ब्रांड अनुभवों पर रखें (Stash) या हटाएं (Trash) में वोट करें।",
      tagline: "हर फैसला ब्रांड्स को लोगों के करीब लाता है। अपना फैसला दें। 🔥",
      tapCoin: "स्टैश देखने के लिए सोने के सिक्के पर टैप करें",
      tapBin: "ट्रैश देखने के लिए बिन पर टैप करें",
      trustScore: "विश्वास स्कोर",
      liveSentiment: "ब्रांड्स पर लाइव जनमत",
      gettingStashed: "जिन्हें सबसे ज़्यादा रखा जा रहा है",
      gettingTrashed: "जिन्हें सबसे ज़्यादा हटाया जा रहा है",
      sotAwards: "SOT पुरस्कार",
      goToDashboard: "डैशबोर्ड पर जाएं",
      exploreFeed: "फ़ीड देखें",
      scanProduct: "उत्पाद स्कैन करें",
      stashes: "रखें (Stashes)",
      trashes: "हटाएं (Trashes)",
    },
  },
  zh: {
    nav: {
      home: "首页",
      feed: "动态",
      scan: "扫码验真",
      brands: "品牌库",
      awards: "年度大奖",
      dashboard: "品牌控制台",
      profile: "个人主页",
      messages: "消息",
      signIn: "登录",
      signUp: "注册",
      signOut: "退出",
    },
    hero: {
      badge: "全球品牌信任晴雨表",
      headlineBlack: "保留值得信赖的好物。",
      headlineGold: "曝光名不副实的槽点。",
      subtitle: "根据您的真实消费体验投出 珍藏 (Stash) 或 吐槽 (Trash) — 最真实的客户体验信号。",
      tagline: "每一次真实裁决都让品牌更贴近消费者。立即投票！🔥",
      tapCoin: "点击金币查看珍藏榜",
      tapBin: "点击垃圾桶查看吐槽榜",
      trustScore: "信任指数",
      liveSentiment: "品牌实时口碑大盘",
      gettingStashed: "今日热门珍藏 (Stashed)",
      gettingTrashed: "今日热门吐槽 (Trashed)",
      sotAwards: "SOT 品牌大奖",
      goToDashboard: "进入品牌管理后台",
      exploreFeed: "浏览社区动态",
      scanProduct: "扫描商品条码验真",
      stashes: "珍藏 (Stashes)",
      trashes: "吐槽 (Trashes)",
    },
  },
  ja: {
    nav: {
      home: "ホーム",
      feed: "フィード",
      scan: "スキャン",
      brands: "ブランド",
      awards: "アワード",
      dashboard: "ダッシュボード",
      profile: "プロフィール",
      messages: "メッセージ",
      signIn: "ログイン",
      signUp: "新規登録",
      signOut: "ログアウト",
    },
    hero: {
      badge: "ブランド信頼バロメーター",
      headlineBlack: "価値あるものを残し、",
      headlineGold: "不誠実なものに声を上げよう。",
      subtitle: "実際のブランド体験に基づいて「キープ (Stash)」か「トラッシュ (Trash)」を投票しましょう。",
      tagline: "すべての評決がブランドと消費者を近づけます。あなたの一票を。🔥",
      tapCoin: "金貨をタップしてキープ一覧を表示",
      tapBin: "ゴミ箱をタップしてトラッシュ一覧を表示",
      trustScore: "信頼スコア",
      liveSentiment: "リアルタイム・ブランド評価",
      gettingStashed: "人気のキープ (Stashed)",
      gettingTrashed: "注目のトラッシュ (Trashed)",
      sotAwards: "SOT アワード",
      goToDashboard: "ダッシュボードへ",
      exploreFeed: "フィードを見る",
      scanProduct: "商品をスキャン",
      stashes: "キープ (Stashes)",
      trashes: "トラッシュ (Trashes)",
    },
  },
  ko: {
    nav: {
      home: "홈",
      feed: "피드",
      scan: "스캔",
      brands: "브랜드",
      awards: "어워드",
      dashboard: "대시보드",
      profile: "프로필",
      messages: "메시지",
      signIn: "로그인",
      signUp: "회원가입",
      signOut: "로그아웃",
    },
    hero: {
      badge: "브랜드 신뢰도 바로미터",
      headlineBlack: "가치 있는 브랜드는 간직하고,",
      headlineGold: "실망스러운 경험에는 목소리를 내세요.",
      subtitle: "실제 브랜드 경험을 바탕으로 보관(Stash) 또는 폐기(Trash)에 투표하세요.",
      tagline: "모든 평결이 브랜드를 소비자에게 더 가깝게 만듭니다. 🔥",
      tapCoin: "금화를 탭하여 보관(Stash) 보기",
      tapBin: "휴지통을 탭하여 폐기(Trash) 보기",
      trustScore: "신뢰 점수",
      liveSentiment: "실시간 브랜드 민심",
      gettingStashed: "인기 보관 브랜드",
      gettingTrashed: "집중 제보 브랜드",
      sotAwards: "SOT 어워드",
      goToDashboard: "브랜드 대시보드로 이동",
      exploreFeed: "피드 둘러보기",
      scanProduct: "바코드/정품 스캔",
      stashes: "보관 (Stashes)",
      trashes: "폐기 (Trashes)",
    },
  },
};
